title: TOPE
description: Trinity Open Psychological Experiments
theme: just-the-docs
logo: "./data/logo.png"

url: https://mklab-japan.github.io/tope

aux_links:
  GitHub: https://github.com/mklab-japan/tope

color_scheme: tope

nav_enabled: true

callouts: 
  note: 
    title: note
    color: blue