title: OPE
description: Open Psychological Experiments
theme: just-the-docs

url: https://mklab-japan.github.io/ope

aux_links:
  GitHub: https://github.com/mklab-japan/ope

color_scheme: ope

nav_enabled: true