title: TOPE
description: Trinity Open Psychological Experiments
theme: just-the-docs

logo: "/data/logo.png"

url: https://mklab-japan.github.io/tope

aux_links:
  GitHub: https://github.com/mklab-japan/tope

color_scheme: tope

nav_enabled: true

callouts:
  memo:
    titile: 📝メモ
    color: blue
  warning:
    titile: ⚠注意
    color: red
  points:
    titile: 💡ポイント
    color: yellow