title: Open Psychological Experiments
description: You can participate in open psychological experiments
theme: just-the-docs

url: https://mklab-japan.github.io/ope

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: ope